version: "3.1"
services:
    mysql:
      image: mysql:8.0
      container_name: trading-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=20207a63f0901ea878fc
        - MYSQL_DATABASE=stock
        - MYSQL_USER=trading
        - MYSQL_PASSWORD=12345678
      ports:
        - "3307:3306"

    php:
      build: ./
      container_name: trading-php
      links:
        - mysql:mysql
      ports:
        - "9001:9000"
      volumes:
        - .:/application
        - ./:/var/www/html
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    webserver:
      image: nginx:1.18
      container_name: trading-webserver
      working_dir: /application
      links:
        - php:fpm
      volumes:
        - .:/application
        - ./:/var/www/html
        - ./storage/logs/nginx/:/var/log/nginx
        - ./docker/nginx_conf:/etc/nginx/conf.d/
      ports:
       - "8080:80"
